#!/usr/local/bin/node

var express = require('express');
var app = express();

console.log(process.geteuid());

app.get('/', function (req, res) {
    res.send('Hello World!');
});

app.listen(8080, function () {
    console.log('Example app listening on port 8080!');
});